### ISSUE TITLE
Meta data of an experiment associated by trial

### ISSUE THREAD

**Issue by dekz** [andrew/split#288]
I've noticed a pattern of using a lookup table inside of the code around the experiment to actually find the correct value based off my alternative.

Code like the following (just a painful example)
```ruby
 if (trial.alternative == "a")
  # get the greeting for A
 else (trial.alternative == "b")
  # get the greeting for B
 end
```

What I would like is the ability for this to be attached to the Trial object itself, and populated at Experiment creation (in YAML).

```yaml
my_first_experiment:
  alternatives:
    - a
    - b
  meta:
     a:
       text: "Have a fantastic day"
     b:
       text: "Don't get hit by a bus"
```

``` ruby
> trial.alternative
# "a"
> trial.meta['text']
# "Have a fantastic day"
```

I'm willing to do the PR, just wanted to get others thoughts on this.
